USB_VID = 0x239A
USB_PID = 0x8084
USB_PRODUCT = "iMX RT 1170 EVK"
USB_MANUFACTURER = "NXP"

CHIP_VARIANT = MIMXRT1176DVMAA_cm7
CHIP_FAMILY = MIMXRT1176
CHIP_CORE = $(CHIP_FAMILY)_cm7
FLASH = IS25WP128

CIRCUITPY_USB_HOST = 0

CIRCUITPY_ANALOGIO = 0
CIRCUITPY_AUDIOBUSIO = 0
CIRCUITPY_AUDIOPWMIO = 0
CIRCUITPY_RANDOM = 0
CIRCUITPY_PWMIO = 0
CIRCUITPY_DISPLAYIO = 0
CIRCUITPY_SDCARDIO = 0
CIRCUITPY_BLEIO = 0
CIRCUITPY_BLEIO_HCI = 0
