//--------------------------------------------------------------------------------
// Auto-generated by Migen (12e7ba6) & LiteX (e7646416) on 2020-07-11 11:48:20
//--------------------------------------------------------------------------------
#include <generated/soc.h>
#ifndef __GENERATED_CSR_H
#define __GENERATED_CSR_H
#include <stdint.h>
//#include <system.h>
#ifndef CSR_ACCESSORS_DEFINED
#include <hw/common.h>
#endif /* ! CSR_ACCESSORS_DEFINED */
#ifndef CSR_BASE
#define CSR_BASE 0x82000000L
#endif

/* ctrl */
#define CSR_CTRL_BASE (CSR_BASE + 0x0L)
#define CSR_CTRL_RESET_ADDR (CSR_BASE + 0x0L)
#define CSR_CTRL_RESET_SIZE 1
static inline uint32_t ctrl_reset_read(void) {
	return csr_read_simple(CSR_BASE + 0x0L);
}
static inline void ctrl_reset_write(uint32_t v) {
	csr_write_simple(v, CSR_BASE + 0x0L);
}
#define CSR_CTRL_SCRATCH_ADDR (CSR_BASE + 0x4L)
#define CSR_CTRL_SCRATCH_SIZE 1
static inline uint32_t ctrl_scratch_read(void) {
	return csr_read_simple(CSR_BASE + 0x4L);
}
static inline void ctrl_scratch_write(uint32_t v) {
	csr_write_simple(v, CSR_BASE + 0x4L);
}
#define CSR_CTRL_BUS_ERRORS_ADDR (CSR_BASE + 0x8L)
#define CSR_CTRL_BUS_ERRORS_SIZE 1
static inline uint32_t ctrl_bus_errors_read(void) {
	return csr_read_simple(CSR_BASE + 0x8L);
}

/* timer0 */
#define CSR_TIMER0_BASE (CSR_BASE + 0x2800L)
#define CSR_TIMER0_LOAD_ADDR (CSR_BASE + 0x2800L)
#define CSR_TIMER0_LOAD_SIZE 1
static inline uint32_t timer0_load_read(void) {
	return csr_read_simple(CSR_BASE + 0x2800L);
}
static inline void timer0_load_write(uint32_t v) {
	csr_write_simple(v, CSR_BASE + 0x2800L);
}
#define CSR_TIMER0_RELOAD_ADDR (CSR_BASE + 0x2804L)
#define CSR_TIMER0_RELOAD_SIZE 1
static inline uint32_t timer0_reload_read(void) {
	return csr_read_simple(CSR_BASE + 0x2804L);
}
static inline void timer0_reload_write(uint32_t v) {
	csr_write_simple(v, CSR_BASE + 0x2804L);
}
#define CSR_TIMER0_EN_ADDR (CSR_BASE + 0x2808L)
#define CSR_TIMER0_EN_SIZE 1
static inline uint32_t timer0_en_read(void) {
	return csr_read_simple(CSR_BASE + 0x2808L);
}
static inline void timer0_en_write(uint32_t v) {
	csr_write_simple(v, CSR_BASE + 0x2808L);
}
#define CSR_TIMER0_UPDATE_VALUE_ADDR (CSR_BASE + 0x280cL)
#define CSR_TIMER0_UPDATE_VALUE_SIZE 1
static inline uint32_t timer0_update_value_read(void) {
	return csr_read_simple(CSR_BASE + 0x280cL);
}
static inline void timer0_update_value_write(uint32_t v) {
	csr_write_simple(v, CSR_BASE + 0x280cL);
}
#define CSR_TIMER0_VALUE_ADDR (CSR_BASE + 0x2810L)
#define CSR_TIMER0_VALUE_SIZE 1
static inline uint32_t timer0_value_read(void) {
	return csr_read_simple(CSR_BASE + 0x2810L);
}
#define CSR_TIMER0_EV_STATUS_ADDR (CSR_BASE + 0x2814L)
#define CSR_TIMER0_EV_STATUS_SIZE 1
static inline uint32_t timer0_ev_status_read(void) {
	return csr_read_simple(CSR_BASE + 0x2814L);
}
static inline void timer0_ev_status_write(uint32_t v) {
	csr_write_simple(v, CSR_BASE + 0x2814L);
}
#define CSR_TIMER0_EV_PENDING_ADDR (CSR_BASE + 0x2818L)
#define CSR_TIMER0_EV_PENDING_SIZE 1
static inline uint32_t timer0_ev_pending_read(void) {
	return csr_read_simple(CSR_BASE + 0x2818L);
}
static inline void timer0_ev_pending_write(uint32_t v) {
	csr_write_simple(v, CSR_BASE + 0x2818L);
}
#define CSR_TIMER0_EV_ENABLE_ADDR (CSR_BASE + 0x281cL)
#define CSR_TIMER0_EV_ENABLE_SIZE 1
static inline uint32_t timer0_ev_enable_read(void) {
	return csr_read_simple(CSR_BASE + 0x281cL);
}
static inline void timer0_ev_enable_write(uint32_t v) {
	csr_write_simple(v, CSR_BASE + 0x281cL);
}

/* uart */
#define CSR_UART_BASE (CSR_BASE + 0x3000L)
#define CSR_UART_RXTX_ADDR (CSR_BASE + 0x3000L)
#define CSR_UART_RXTX_SIZE 1
static inline uint32_t uart_rxtx_read(void) {
	return csr_read_simple(CSR_BASE + 0x3000L);
}
static inline void uart_rxtx_write(uint32_t v) {
	csr_write_simple(v, CSR_BASE + 0x3000L);
}
#define CSR_UART_TXFULL_ADDR (CSR_BASE + 0x3004L)
#define CSR_UART_TXFULL_SIZE 1
static inline uint32_t uart_txfull_read(void) {
	return csr_read_simple(CSR_BASE + 0x3004L);
}
#define CSR_UART_RXEMPTY_ADDR (CSR_BASE + 0x3008L)
#define CSR_UART_RXEMPTY_SIZE 1
static inline uint32_t uart_rxempty_read(void) {
	return csr_read_simple(CSR_BASE + 0x3008L);
}
#define CSR_UART_EV_STATUS_ADDR (CSR_BASE + 0x300cL)
#define CSR_UART_EV_STATUS_SIZE 1
static inline uint32_t uart_ev_status_read(void) {
	return csr_read_simple(CSR_BASE + 0x300cL);
}
static inline void uart_ev_status_write(uint32_t v) {
	csr_write_simple(v, CSR_BASE + 0x300cL);
}
#define CSR_UART_EV_PENDING_ADDR (CSR_BASE + 0x3010L)
#define CSR_UART_EV_PENDING_SIZE 1
static inline uint32_t uart_ev_pending_read(void) {
	return csr_read_simple(CSR_BASE + 0x3010L);
}
static inline void uart_ev_pending_write(uint32_t v) {
	csr_write_simple(v, CSR_BASE + 0x3010L);
}
#define CSR_UART_EV_ENABLE_ADDR (CSR_BASE + 0x3014L)
#define CSR_UART_EV_ENABLE_SIZE 1
static inline uint32_t uart_ev_enable_read(void) {
	return csr_read_simple(CSR_BASE + 0x3014L);
}
static inline void uart_ev_enable_write(uint32_t v) {
	csr_write_simple(v, CSR_BASE + 0x3014L);
}

/* ddrphy */
#define CSR_DDRPHY_BASE (CSR_BASE + 0x3800L)
#define CSR_DDRPHY_DLY_SEL_ADDR (CSR_BASE + 0x3800L)
#define CSR_DDRPHY_DLY_SEL_SIZE 1
static inline uint32_t ddrphy_dly_sel_read(void) {
	return csr_read_simple(CSR_BASE + 0x3800L);
}
static inline void ddrphy_dly_sel_write(uint32_t v) {
	csr_write_simple(v, CSR_BASE + 0x3800L);
}
#define CSR_DDRPHY_RDLY_DQ_RST_ADDR (CSR_BASE + 0x3804L)
#define CSR_DDRPHY_RDLY_DQ_RST_SIZE 1
static inline uint32_t ddrphy_rdly_dq_rst_read(void) {
	return csr_read_simple(CSR_BASE + 0x3804L);
}
static inline void ddrphy_rdly_dq_rst_write(uint32_t v) {
	csr_write_simple(v, CSR_BASE + 0x3804L);
}
#define CSR_DDRPHY_RDLY_DQ_INC_ADDR (CSR_BASE + 0x3808L)
#define CSR_DDRPHY_RDLY_DQ_INC_SIZE 1
static inline uint32_t ddrphy_rdly_dq_inc_read(void) {
	return csr_read_simple(CSR_BASE + 0x3808L);
}
static inline void ddrphy_rdly_dq_inc_write(uint32_t v) {
	csr_write_simple(v, CSR_BASE + 0x3808L);
}
#define CSR_DDRPHY_RDLY_DQ_BITSLIP_RST_ADDR (CSR_BASE + 0x380cL)
#define CSR_DDRPHY_RDLY_DQ_BITSLIP_RST_SIZE 1
static inline uint32_t ddrphy_rdly_dq_bitslip_rst_read(void) {
	return csr_read_simple(CSR_BASE + 0x380cL);
}
static inline void ddrphy_rdly_dq_bitslip_rst_write(uint32_t v) {
	csr_write_simple(v, CSR_BASE + 0x380cL);
}
#define CSR_DDRPHY_RDLY_DQ_BITSLIP_ADDR (CSR_BASE + 0x3810L)
#define CSR_DDRPHY_RDLY_DQ_BITSLIP_SIZE 1
static inline uint32_t ddrphy_rdly_dq_bitslip_read(void) {
	return csr_read_simple(CSR_BASE + 0x3810L);
}
static inline void ddrphy_rdly_dq_bitslip_write(uint32_t v) {
	csr_write_simple(v, CSR_BASE + 0x3810L);
}
#define CSR_DDRPHY_BURSTDET_CLR_ADDR (CSR_BASE + 0x3814L)
#define CSR_DDRPHY_BURSTDET_CLR_SIZE 1
static inline uint32_t ddrphy_burstdet_clr_read(void) {
	return csr_read_simple(CSR_BASE + 0x3814L);
}
static inline void ddrphy_burstdet_clr_write(uint32_t v) {
	csr_write_simple(v, CSR_BASE + 0x3814L);
}
#define CSR_DDRPHY_BURSTDET_SEEN_ADDR (CSR_BASE + 0x3818L)
#define CSR_DDRPHY_BURSTDET_SEEN_SIZE 1
static inline uint32_t ddrphy_burstdet_seen_read(void) {
	return csr_read_simple(CSR_BASE + 0x3818L);
}

/* sdram */
#define CSR_SDRAM_BASE (CSR_BASE + 0x4000L)
#define CSR_SDRAM_DFII_CONTROL_ADDR (CSR_BASE + 0x4000L)
#define CSR_SDRAM_DFII_CONTROL_SIZE 1
static inline uint32_t sdram_dfii_control_read(void) {
	return csr_read_simple(CSR_BASE + 0x4000L);
}
static inline void sdram_dfii_control_write(uint32_t v) {
	csr_write_simple(v, CSR_BASE + 0x4000L);
}
#define CSR_SDRAM_DFII_CONTROL_SEL_OFFSET 0
#define CSR_SDRAM_DFII_CONTROL_SEL_SIZE 1
#define CSR_SDRAM_DFII_CONTROL_CKE_OFFSET 1
#define CSR_SDRAM_DFII_CONTROL_CKE_SIZE 1
#define CSR_SDRAM_DFII_CONTROL_ODT_OFFSET 2
#define CSR_SDRAM_DFII_CONTROL_ODT_SIZE 1
#define CSR_SDRAM_DFII_CONTROL_RESET_N_OFFSET 3
#define CSR_SDRAM_DFII_CONTROL_RESET_N_SIZE 1
#define CSR_SDRAM_DFII_PI0_COMMAND_ADDR (CSR_BASE + 0x4004L)
#define CSR_SDRAM_DFII_PI0_COMMAND_SIZE 1
static inline uint32_t sdram_dfii_pi0_command_read(void) {
	return csr_read_simple(CSR_BASE + 0x4004L);
}
static inline void sdram_dfii_pi0_command_write(uint32_t v) {
	csr_write_simple(v, CSR_BASE + 0x4004L);
}
#define CSR_SDRAM_DFII_PI0_COMMAND_ISSUE_ADDR (CSR_BASE + 0x4008L)
#define CSR_SDRAM_DFII_PI0_COMMAND_ISSUE_SIZE 1
static inline uint32_t sdram_dfii_pi0_command_issue_read(void) {
	return csr_read_simple(CSR_BASE + 0x4008L);
}
static inline void sdram_dfii_pi0_command_issue_write(uint32_t v) {
	csr_write_simple(v, CSR_BASE + 0x4008L);
}
#define CSR_SDRAM_DFII_PI0_ADDRESS_ADDR (CSR_BASE + 0x400cL)
#define CSR_SDRAM_DFII_PI0_ADDRESS_SIZE 1
static inline uint32_t sdram_dfii_pi0_address_read(void) {
	return csr_read_simple(CSR_BASE + 0x400cL);
}
static inline void sdram_dfii_pi0_address_write(uint32_t v) {
	csr_write_simple(v, CSR_BASE + 0x400cL);
}
#define CSR_SDRAM_DFII_PI0_BADDRESS_ADDR (CSR_BASE + 0x4010L)
#define CSR_SDRAM_DFII_PI0_BADDRESS_SIZE 1
static inline uint32_t sdram_dfii_pi0_baddress_read(void) {
	return csr_read_simple(CSR_BASE + 0x4010L);
}
static inline void sdram_dfii_pi0_baddress_write(uint32_t v) {
	csr_write_simple(v, CSR_BASE + 0x4010L);
}
#define CSR_SDRAM_DFII_PI0_WRDATA_ADDR (CSR_BASE + 0x4014L)
#define CSR_SDRAM_DFII_PI0_WRDATA_SIZE 2
static inline uint64_t sdram_dfii_pi0_wrdata_read(void) {
	uint64_t r = csr_read_simple(CSR_BASE + 0x4014L);
	r <<= 32;
	r |= csr_read_simple(CSR_BASE + 0x4018L);
	return r;
}
static inline void sdram_dfii_pi0_wrdata_write(uint64_t v) {
	csr_write_simple(v >> 32, CSR_BASE + 0x4014L);
	csr_write_simple(v, CSR_BASE + 0x4018L);
}
#define CSR_SDRAM_DFII_PI0_RDDATA_ADDR (CSR_BASE + 0x401cL)
#define CSR_SDRAM_DFII_PI0_RDDATA_SIZE 2
static inline uint64_t sdram_dfii_pi0_rddata_read(void) {
	uint64_t r = csr_read_simple(CSR_BASE + 0x401cL);
	r <<= 32;
	r |= csr_read_simple(CSR_BASE + 0x4020L);
	return r;
}
#define CSR_SDRAM_DFII_PI1_COMMAND_ADDR (CSR_BASE + 0x4024L)
#define CSR_SDRAM_DFII_PI1_COMMAND_SIZE 1
static inline uint32_t sdram_dfii_pi1_command_read(void) {
	return csr_read_simple(CSR_BASE + 0x4024L);
}
static inline void sdram_dfii_pi1_command_write(uint32_t v) {
	csr_write_simple(v, CSR_BASE + 0x4024L);
}
#define CSR_SDRAM_DFII_PI1_COMMAND_ISSUE_ADDR (CSR_BASE + 0x4028L)
#define CSR_SDRAM_DFII_PI1_COMMAND_ISSUE_SIZE 1
static inline uint32_t sdram_dfii_pi1_command_issue_read(void) {
	return csr_read_simple(CSR_BASE + 0x4028L);
}
static inline void sdram_dfii_pi1_command_issue_write(uint32_t v) {
	csr_write_simple(v, CSR_BASE + 0x4028L);
}
#define CSR_SDRAM_DFII_PI1_ADDRESS_ADDR (CSR_BASE + 0x402cL)
#define CSR_SDRAM_DFII_PI1_ADDRESS_SIZE 1
static inline uint32_t sdram_dfii_pi1_address_read(void) {
	return csr_read_simple(CSR_BASE + 0x402cL);
}
static inline void sdram_dfii_pi1_address_write(uint32_t v) {
	csr_write_simple(v, CSR_BASE + 0x402cL);
}
#define CSR_SDRAM_DFII_PI1_BADDRESS_ADDR (CSR_BASE + 0x4030L)
#define CSR_SDRAM_DFII_PI1_BADDRESS_SIZE 1
static inline uint32_t sdram_dfii_pi1_baddress_read(void) {
	return csr_read_simple(CSR_BASE + 0x4030L);
}
static inline void sdram_dfii_pi1_baddress_write(uint32_t v) {
	csr_write_simple(v, CSR_BASE + 0x4030L);
}
#define CSR_SDRAM_DFII_PI1_WRDATA_ADDR (CSR_BASE + 0x4034L)
#define CSR_SDRAM_DFII_PI1_WRDATA_SIZE 2
static inline uint64_t sdram_dfii_pi1_wrdata_read(void) {
	uint64_t r = csr_read_simple(CSR_BASE + 0x4034L);
	r <<= 32;
	r |= csr_read_simple(CSR_BASE + 0x4038L);
	return r;
}
static inline void sdram_dfii_pi1_wrdata_write(uint64_t v) {
	csr_write_simple(v >> 32, CSR_BASE + 0x4034L);
	csr_write_simple(v, CSR_BASE + 0x4038L);
}
#define CSR_SDRAM_DFII_PI1_RDDATA_ADDR (CSR_BASE + 0x403cL)
#define CSR_SDRAM_DFII_PI1_RDDATA_SIZE 2
static inline uint64_t sdram_dfii_pi1_rddata_read(void) {
	uint64_t r = csr_read_simple(CSR_BASE + 0x403cL);
	r <<= 32;
	r |= csr_read_simple(CSR_BASE + 0x4040L);
	return r;
}

/* rgb */
#define CSR_RGB_BASE (CSR_BASE + 0x5000L)
#define CSR_RGB_R_ADDR (CSR_BASE + 0x5000L)
#define CSR_RGB_R_SIZE 1
static inline uint32_t rgb_r_read(void) {
	return csr_read_simple(CSR_BASE + 0x5000L);
}
static inline void rgb_r_write(uint32_t v) {
	csr_write_simple(v, CSR_BASE + 0x5000L);
}
#define CSR_RGB_G_ADDR (CSR_BASE + 0x5004L)
#define CSR_RGB_G_SIZE 1
static inline uint32_t rgb_g_read(void) {
	return csr_read_simple(CSR_BASE + 0x5004L);
}
static inline void rgb_g_write(uint32_t v) {
	csr_write_simple(v, CSR_BASE + 0x5004L);
}
#define CSR_RGB_B_ADDR (CSR_BASE + 0x5008L)
#define CSR_RGB_B_SIZE 1
static inline uint32_t rgb_b_read(void) {
	return csr_read_simple(CSR_BASE + 0x5008L);
}
static inline void rgb_b_write(uint32_t v) {
	csr_write_simple(v, CSR_BASE + 0x5008L);
}
#define CSR_RGB_DIV_M_ADDR (CSR_BASE + 0x500cL)
#define CSR_RGB_DIV_M_SIZE 1
static inline uint32_t rgb_div_m_read(void) {
	return csr_read_simple(CSR_BASE + 0x500cL);
}
static inline void rgb_div_m_write(uint32_t v) {
	csr_write_simple(v, CSR_BASE + 0x500cL);
}
#define CSR_RGB_CONFIG_ADDR (CSR_BASE + 0x5010L)
#define CSR_RGB_CONFIG_SIZE 1
static inline uint32_t rgb_config_read(void) {
	return csr_read_simple(CSR_BASE + 0x5010L);
}
static inline void rgb_config_write(uint32_t v) {
	csr_write_simple(v, CSR_BASE + 0x5010L);
}
#define CSR_RGB_CONFIG_BREATH_OFFSET 0
#define CSR_RGB_CONFIG_BREATH_SIZE 1
#define CSR_RGB_CONFIG_RAINBOW_OFFSET 1
#define CSR_RGB_CONFIG_RAINBOW_SIZE 1

/* gpio */
#define CSR_GPIO_BASE (CSR_BASE + 0x5800L)
#define CSR_GPIO_OE_ADDR (CSR_BASE + 0x5800L)
#define CSR_GPIO_OE_SIZE 1
static inline uint32_t gpio_oe_read(void) {
	return csr_read_simple(CSR_BASE + 0x5800L);
}
static inline void gpio_oe_write(uint32_t v) {
	csr_write_simple(v, CSR_BASE + 0x5800L);
}
#define CSR_GPIO_OE_IO6_OFFSET 6
#define CSR_GPIO_OE_IO6_SIZE 1
#define CSR_GPIO_OE_IO9_OFFSET 9
#define CSR_GPIO_OE_IO9_SIZE 1
#define CSR_GPIO_OE_IO10_OFFSET 10
#define CSR_GPIO_OE_IO10_SIZE 1
#define CSR_GPIO_OE_IO11_OFFSET 11
#define CSR_GPIO_OE_IO11_SIZE 1
#define CSR_GPIO_OE_IO12_OFFSET 12
#define CSR_GPIO_OE_IO12_SIZE 1
#define CSR_GPIO_OE_IO13_OFFSET 13
#define CSR_GPIO_OE_IO13_SIZE 1
#define CSR_GPIO_OE_IO18_OFFSET 18
#define CSR_GPIO_OE_IO18_SIZE 1
#define CSR_GPIO_OE_IO19_OFFSET 19
#define CSR_GPIO_OE_IO19_SIZE 1
#define CSR_GPIO_OE_IO20_OFFSET 20
#define CSR_GPIO_OE_IO20_SIZE 1
#define CSR_GPIO_OE_IO21_OFFSET 21
#define CSR_GPIO_OE_IO21_SIZE 1
#define CSR_GPIO_IN_ADDR (CSR_BASE + 0x5804L)
#define CSR_GPIO_IN_SIZE 1
static inline uint32_t gpio_in_read(void) {
	return csr_read_simple(CSR_BASE + 0x5804L);
}
#define CSR_GPIO_IN_IO6_OFFSET 6
#define CSR_GPIO_IN_IO6_SIZE 1
#define CSR_GPIO_IN_IO9_OFFSET 9
#define CSR_GPIO_IN_IO9_SIZE 1
#define CSR_GPIO_IN_IO10_OFFSET 10
#define CSR_GPIO_IN_IO10_SIZE 1
#define CSR_GPIO_IN_IO11_OFFSET 11
#define CSR_GPIO_IN_IO11_SIZE 1
#define CSR_GPIO_IN_IO12_OFFSET 12
#define CSR_GPIO_IN_IO12_SIZE 1
#define CSR_GPIO_IN_IO13_OFFSET 13
#define CSR_GPIO_IN_IO13_SIZE 1
#define CSR_GPIO_IN_IO18_OFFSET 18
#define CSR_GPIO_IN_IO18_SIZE 1
#define CSR_GPIO_IN_IO19_OFFSET 19
#define CSR_GPIO_IN_IO19_SIZE 1
#define CSR_GPIO_IN_IO20_OFFSET 20
#define CSR_GPIO_IN_IO20_SIZE 1
#define CSR_GPIO_IN_IO21_OFFSET 21
#define CSR_GPIO_IN_IO21_SIZE 1
#define CSR_GPIO_OUT_ADDR (CSR_BASE + 0x5808L)
#define CSR_GPIO_OUT_SIZE 1
static inline uint32_t gpio_out_read(void) {
	return csr_read_simple(CSR_BASE + 0x5808L);
}
static inline void gpio_out_write(uint32_t v) {
	csr_write_simple(v, CSR_BASE + 0x5808L);
}
#define CSR_GPIO_OUT_IO6_OFFSET 6
#define CSR_GPIO_OUT_IO6_SIZE 1
#define CSR_GPIO_OUT_IO9_OFFSET 9
#define CSR_GPIO_OUT_IO9_SIZE 1
#define CSR_GPIO_OUT_IO10_OFFSET 10
#define CSR_GPIO_OUT_IO10_SIZE 1
#define CSR_GPIO_OUT_IO11_OFFSET 11
#define CSR_GPIO_OUT_IO11_SIZE 1
#define CSR_GPIO_OUT_IO12_OFFSET 12
#define CSR_GPIO_OUT_IO12_SIZE 1
#define CSR_GPIO_OUT_IO13_OFFSET 13
#define CSR_GPIO_OUT_IO13_SIZE 1
#define CSR_GPIO_OUT_IO18_OFFSET 18
#define CSR_GPIO_OUT_IO18_SIZE 1
#define CSR_GPIO_OUT_IO19_OFFSET 19
#define CSR_GPIO_OUT_IO19_SIZE 1
#define CSR_GPIO_OUT_IO20_OFFSET 20
#define CSR_GPIO_OUT_IO20_SIZE 1
#define CSR_GPIO_OUT_IO21_OFFSET 21
#define CSR_GPIO_OUT_IO21_SIZE 1

/* lxspi */
#define CSR_LXSPI_BASE (CSR_BASE + 0x7800L)
#define CSR_LXSPI_BITBANG_ADDR (CSR_BASE + 0x7800L)
#define CSR_LXSPI_BITBANG_SIZE 1
static inline uint32_t lxspi_bitbang_read(void) {
	return csr_read_simple(CSR_BASE + 0x7800L);
}
static inline void lxspi_bitbang_write(uint32_t v) {
	csr_write_simple(v, CSR_BASE + 0x7800L);
}
#define CSR_LXSPI_BITBANG_MOSI_OFFSET 0
#define CSR_LXSPI_BITBANG_MOSI_SIZE 1
#define CSR_LXSPI_BITBANG_CLK_OFFSET 1
#define CSR_LXSPI_BITBANG_CLK_SIZE 1
#define CSR_LXSPI_BITBANG_CS_N_OFFSET 2
#define CSR_LXSPI_BITBANG_CS_N_SIZE 1
#define CSR_LXSPI_BITBANG_DIR_OFFSET 3
#define CSR_LXSPI_BITBANG_DIR_SIZE 1
#define CSR_LXSPI_MISO_ADDR (CSR_BASE + 0x7804L)
#define CSR_LXSPI_MISO_SIZE 1
static inline uint32_t lxspi_miso_read(void) {
	return csr_read_simple(CSR_BASE + 0x7804L);
}
#define CSR_LXSPI_BITBANG_EN_ADDR (CSR_BASE + 0x7808L)
#define CSR_LXSPI_BITBANG_EN_SIZE 1
static inline uint32_t lxspi_bitbang_en_read(void) {
	return csr_read_simple(CSR_BASE + 0x7808L);
}
static inline void lxspi_bitbang_en_write(uint32_t v) {
	csr_write_simple(v, CSR_BASE + 0x7808L);
}

/* button */
#define CSR_BUTTON_BASE (CSR_BASE + 0x8800L)
#define CSR_BUTTON_IN_ADDR (CSR_BASE + 0x8800L)
#define CSR_BUTTON_IN_SIZE 1
static inline uint32_t button_in_read(void) {
	return csr_read_simple(CSR_BASE + 0x8800L);
}

/* asense */
#define CSR_ASENSE_BASE (CSR_BASE + 0x9000L)
#define CSR_ASENSE_CONTROL_ADDR (CSR_BASE + 0x9000L)
#define CSR_ASENSE_CONTROL_SIZE 1
static inline uint32_t asense_control_read(void) {
	return csr_read_simple(CSR_BASE + 0x9000L);
}
static inline void asense_control_write(uint32_t v) {
	csr_write_simple(v, CSR_BASE + 0x9000L);
}
#define CSR_ASENSE_CONTROL_START_OFFSET 0
#define CSR_ASENSE_CONTROL_START_SIZE 1
#define CSR_ASENSE_CONTROL_CHAN_OFFSET 8
#define CSR_ASENSE_CONTROL_CHAN_SIZE 4
#define CSR_ASENSE_STATUS_ADDR (CSR_BASE + 0x9004L)
#define CSR_ASENSE_STATUS_SIZE 1
static inline uint32_t asense_status_read(void) {
	return csr_read_simple(CSR_BASE + 0x9004L);
}
#define CSR_ASENSE_STATUS_IDLE_OFFSET 0
#define CSR_ASENSE_STATUS_IDLE_SIZE 1
#define CSR_ASENSE_RESULT_ADDR (CSR_BASE + 0x9008L)
#define CSR_ASENSE_RESULT_SIZE 1
static inline uint32_t asense_result_read(void) {
	return csr_read_simple(CSR_BASE + 0x9008L);
}



/* usb */
#define CSR_USB_BASE (0x90000000 + 0x0L)
#define CSR_USB_PULLUP_OUT_ADDR (0x90000000 + 0x0L)
#define CSR_USB_PULLUP_OUT_SIZE 1
static inline uint32_t usb_pullup_out_read(void) {
	return csr_read_simple(0x90000000 + 0x0L);
}
static inline void usb_pullup_out_write(uint32_t v) {
	csr_write_simple(v, 0x90000000 + 0x0L);
}
#define CSR_USB_ADDRESS_ADDR (0x90000000 + 0x4L)
#define CSR_USB_ADDRESS_SIZE 1
static inline uint32_t usb_address_read(void) {
	return csr_read_simple(0x90000000 + 0x4L);
}
static inline void usb_address_write(uint32_t v) {
	csr_write_simple(v, 0x90000000 + 0x4L);
}
#define CSR_USB_ADDRESS_ADDR_OFFSET 0
#define CSR_USB_ADDRESS_ADDR_SIZE 7
#define CSR_USB_NEXT_EV_ADDR (0x90000000 + 0x8L)
#define CSR_USB_NEXT_EV_SIZE 1
static inline uint32_t usb_next_ev_read(void) {
	return csr_read_simple(0x90000000 + 0x8L);
}
#define CSR_USB_NEXT_EV_IN_OFFSET 0
#define CSR_USB_NEXT_EV_IN_SIZE 1
#define CSR_USB_NEXT_EV_OUT_OFFSET 1
#define CSR_USB_NEXT_EV_OUT_SIZE 1
#define CSR_USB_NEXT_EV_SETUP_OFFSET 2
#define CSR_USB_NEXT_EV_SETUP_SIZE 1
#define CSR_USB_NEXT_EV_RESET_OFFSET 3
#define CSR_USB_NEXT_EV_RESET_SIZE 1
#define CSR_USB_SETUP_DATA_ADDR (0x90000000 + 0xcL)
#define CSR_USB_SETUP_DATA_SIZE 1
static inline uint32_t usb_setup_data_read(void) {
	return csr_read_simple(0x90000000 + 0xcL);
}
#define CSR_USB_SETUP_DATA_DATA_OFFSET 0
#define CSR_USB_SETUP_DATA_DATA_SIZE 8
#define CSR_USB_SETUP_CTRL_ADDR (0x90000000 + 0x10L)
#define CSR_USB_SETUP_CTRL_SIZE 1
static inline uint32_t usb_setup_ctrl_read(void) {
	return csr_read_simple(0x90000000 + 0x10L);
}
static inline void usb_setup_ctrl_write(uint32_t v) {
	csr_write_simple(v, 0x90000000 + 0x10L);
}
#define CSR_USB_SETUP_CTRL_RESET_OFFSET 5
#define CSR_USB_SETUP_CTRL_RESET_SIZE 1
#define CSR_USB_SETUP_STATUS_ADDR (0x90000000 + 0x14L)
#define CSR_USB_SETUP_STATUS_SIZE 1
static inline uint32_t usb_setup_status_read(void) {
	return csr_read_simple(0x90000000 + 0x14L);
}
#define CSR_USB_SETUP_STATUS_EPNO_OFFSET 0
#define CSR_USB_SETUP_STATUS_EPNO_SIZE 4
#define CSR_USB_SETUP_STATUS_HAVE_OFFSET 4
#define CSR_USB_SETUP_STATUS_HAVE_SIZE 1
#define CSR_USB_SETUP_STATUS_PEND_OFFSET 5
#define CSR_USB_SETUP_STATUS_PEND_SIZE 1
#define CSR_USB_SETUP_STATUS_IS_IN_OFFSET 6
#define CSR_USB_SETUP_STATUS_IS_IN_SIZE 1
#define CSR_USB_SETUP_STATUS_DATA_OFFSET 7
#define CSR_USB_SETUP_STATUS_DATA_SIZE 1
#define CSR_USB_SETUP_EV_STATUS_ADDR (0x90000000 + 0x18L)
#define CSR_USB_SETUP_EV_STATUS_SIZE 1
static inline uint32_t usb_setup_ev_status_read(void) {
	return csr_read_simple(0x90000000 + 0x18L);
}
static inline void usb_setup_ev_status_write(uint32_t v) {
	csr_write_simple(v, 0x90000000 + 0x18L);
}
#define CSR_USB_SETUP_EV_PENDING_ADDR (0x90000000 + 0x1cL)
#define CSR_USB_SETUP_EV_PENDING_SIZE 1
static inline uint32_t usb_setup_ev_pending_read(void) {
	return csr_read_simple(0x90000000 + 0x1cL);
}
static inline void usb_setup_ev_pending_write(uint32_t v) {
	csr_write_simple(v, 0x90000000 + 0x1cL);
}
#define CSR_USB_SETUP_EV_ENABLE_ADDR (0x90000000 + 0x20L)
#define CSR_USB_SETUP_EV_ENABLE_SIZE 1
static inline uint32_t usb_setup_ev_enable_read(void) {
	return csr_read_simple(0x90000000 + 0x20L);
}
static inline void usb_setup_ev_enable_write(uint32_t v) {
	csr_write_simple(v, 0x90000000 + 0x20L);
}
#define CSR_USB_IN_DATA_ADDR (0x90000000 + 0x24L)
#define CSR_USB_IN_DATA_SIZE 1
static inline uint32_t usb_in_data_read(void) {
	return csr_read_simple(0x90000000 + 0x24L);
}
static inline void usb_in_data_write(uint32_t v) {
	csr_write_simple(v, 0x90000000 + 0x24L);
}
#define CSR_USB_IN_DATA_DATA_OFFSET 0
#define CSR_USB_IN_DATA_DATA_SIZE 8
#define CSR_USB_IN_CTRL_ADDR (0x90000000 + 0x28L)
#define CSR_USB_IN_CTRL_SIZE 1
static inline uint32_t usb_in_ctrl_read(void) {
	return csr_read_simple(0x90000000 + 0x28L);
}
static inline void usb_in_ctrl_write(uint32_t v) {
	csr_write_simple(v, 0x90000000 + 0x28L);
}
#define CSR_USB_IN_CTRL_EPNO_OFFSET 0
#define CSR_USB_IN_CTRL_EPNO_SIZE 4
#define CSR_USB_IN_CTRL_RESET_OFFSET 5
#define CSR_USB_IN_CTRL_RESET_SIZE 1
#define CSR_USB_IN_CTRL_STALL_OFFSET 6
#define CSR_USB_IN_CTRL_STALL_SIZE 1
#define CSR_USB_IN_STATUS_ADDR (0x90000000 + 0x2cL)
#define CSR_USB_IN_STATUS_SIZE 1
static inline uint32_t usb_in_status_read(void) {
	return csr_read_simple(0x90000000 + 0x2cL);
}
#define CSR_USB_IN_STATUS_IDLE_OFFSET 0
#define CSR_USB_IN_STATUS_IDLE_SIZE 1
#define CSR_USB_IN_STATUS_HAVE_OFFSET 4
#define CSR_USB_IN_STATUS_HAVE_SIZE 1
#define CSR_USB_IN_STATUS_PEND_OFFSET 5
#define CSR_USB_IN_STATUS_PEND_SIZE 1
#define CSR_USB_IN_EV_STATUS_ADDR (0x90000000 + 0x30L)
#define CSR_USB_IN_EV_STATUS_SIZE 1
static inline uint32_t usb_in_ev_status_read(void) {
	return csr_read_simple(0x90000000 + 0x30L);
}
static inline void usb_in_ev_status_write(uint32_t v) {
	csr_write_simple(v, 0x90000000 + 0x30L);
}
#define CSR_USB_IN_EV_PENDING_ADDR (0x90000000 + 0x34L)
#define CSR_USB_IN_EV_PENDING_SIZE 1
static inline uint32_t usb_in_ev_pending_read(void) {
	return csr_read_simple(0x90000000 + 0x34L);
}
static inline void usb_in_ev_pending_write(uint32_t v) {
	csr_write_simple(v, 0x90000000 + 0x34L);
}
#define CSR_USB_IN_EV_ENABLE_ADDR (0x90000000 + 0x38L)
#define CSR_USB_IN_EV_ENABLE_SIZE 1
static inline uint32_t usb_in_ev_enable_read(void) {
	return csr_read_simple(0x90000000 + 0x38L);
}
static inline void usb_in_ev_enable_write(uint32_t v) {
	csr_write_simple(v, 0x90000000 + 0x38L);
}
#define CSR_USB_OUT_DATA_ADDR (0x90000000 + 0x3cL)
#define CSR_USB_OUT_DATA_SIZE 1
static inline uint32_t usb_out_data_read(void) {
	return csr_read_simple(0x90000000 + 0x3cL);
}
#define CSR_USB_OUT_DATA_DATA_OFFSET 0
#define CSR_USB_OUT_DATA_DATA_SIZE 8
#define CSR_USB_OUT_CTRL_ADDR (0x90000000 + 0x40L)
#define CSR_USB_OUT_CTRL_SIZE 1
static inline uint32_t usb_out_ctrl_read(void) {
	return csr_read_simple(0x90000000 + 0x40L);
}
static inline void usb_out_ctrl_write(uint32_t v) {
	csr_write_simple(v, 0x90000000 + 0x40L);
}
#define CSR_USB_OUT_CTRL_EPNO_OFFSET 0
#define CSR_USB_OUT_CTRL_EPNO_SIZE 4
#define CSR_USB_OUT_CTRL_ENABLE_OFFSET 4
#define CSR_USB_OUT_CTRL_ENABLE_SIZE 1
#define CSR_USB_OUT_CTRL_RESET_OFFSET 5
#define CSR_USB_OUT_CTRL_RESET_SIZE 1
#define CSR_USB_OUT_CTRL_STALL_OFFSET 6
#define CSR_USB_OUT_CTRL_STALL_SIZE 1
#define CSR_USB_OUT_STATUS_ADDR (0x90000000 + 0x44L)
#define CSR_USB_OUT_STATUS_SIZE 1
static inline uint32_t usb_out_status_read(void) {
	return csr_read_simple(0x90000000 + 0x44L);
}
#define CSR_USB_OUT_STATUS_EPNO_OFFSET 0
#define CSR_USB_OUT_STATUS_EPNO_SIZE 4
#define CSR_USB_OUT_STATUS_HAVE_OFFSET 4
#define CSR_USB_OUT_STATUS_HAVE_SIZE 1
#define CSR_USB_OUT_STATUS_PEND_OFFSET 5
#define CSR_USB_OUT_STATUS_PEND_SIZE 1
#define CSR_USB_OUT_EV_STATUS_ADDR (0x90000000 + 0x48L)
#define CSR_USB_OUT_EV_STATUS_SIZE 1
static inline uint32_t usb_out_ev_status_read(void) {
	return csr_read_simple(0x90000000 + 0x48L);
}
static inline void usb_out_ev_status_write(uint32_t v) {
	csr_write_simple(v, 0x90000000 + 0x48L);
}
#define CSR_USB_OUT_EV_PENDING_ADDR (0x90000000 + 0x4cL)
#define CSR_USB_OUT_EV_PENDING_SIZE 1
static inline uint32_t usb_out_ev_pending_read(void) {
	return csr_read_simple(0x90000000 + 0x4cL);
}
static inline void usb_out_ev_pending_write(uint32_t v) {
	csr_write_simple(v, 0x90000000 + 0x4cL);
}
#define CSR_USB_OUT_EV_ENABLE_ADDR (0x90000000 + 0x50L)
#define CSR_USB_OUT_EV_ENABLE_SIZE 1
static inline uint32_t usb_out_ev_enable_read(void) {
	return csr_read_simple(0x90000000 + 0x50L);
}
static inline void usb_out_ev_enable_write(uint32_t v) {
	csr_write_simple(v, 0x90000000 + 0x50L);
}


#endif
