USB_VID = 0x239A
USB_PID = 0x0000
USB_PRODUCT = "DefCon32 Badge"
USB_MANUFACTURER = "Entropic"

CHIP_VARIANT = RP2350
CHIP_PACKAGE = A
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "W25Q32JVxQ"

CIRCUITPY_ALARM = 0
CIRCUITPY_RGBMATRIX = 0
CIRCUITPY_USB_HOST = 0
CIRCUITPY_FLOPPYIO = 0
