name: Fetch Zephyr port deps

runs:
  using: composite
  steps:
    - name: Setup Zephyr project
      uses: zephyrproject-rtos/action-zephyr-setup@v1
      with:
        app-path: ports/zephyr-cp/zephyr-config
        toolchains: arm-zephyr-eabi
