CONFIG_MULTITHREADING=y

# No gpregret on nrf54h20, disable double-tap reset into UF2.
CONFIG_MCUBOOT_UF2_ENTRANCE_DOUBLE_TAP=n

# nrf54h20 uses MSPI for external flash.
CONFIG_FLASH_MSPI_NOR_LAYOUT_PAGE_SIZE=4096
