# No USB on nrf54l15dk, disable UF2 drag-and-drop.
CONFIG_MCUBOOT_UF2=n

# Enable SPI NOR flash driver for external mx25r64 (slot1).
CONFIG_SPI_NOR=y

# Retained memory for boot mode (double-tap reset).
CONFIG_RETAINED_MEM=y
CONFIG_RETENTION=y
CONFIG_RETENTION_BOOT_MODE=y
