USB_VID = 0x1209
USB_PID = 0xDABB
USB_PRODUCT = "AI-ON-THE-EDGE-CAM"
USB_MANUFACTURER = "Prokyber"

IDF_TARGET = esp32s3

CIRCUITPY_ESP_FLASH_MODE = qio
CIRCUITPY_ESP_FLASH_FREQ = 80m
CIRCUITPY_ESP_FLASH_SIZE = 16MB

CIRCUITPY_ESP_PSRAM_MODE = opi
CIRCUITPY_ESP_PSRAM_FREQ = 80m
CIRCUITPY_ESP_PSRAM_SIZE = 8MB
