#define MICROPY_HW_BOARD_NAME "TinyVision AI Pico Ice"
#define MICROPY_HW_MCU_NAME "rp2040"

#define DEFAULT_SPI_BUS_SCK (&pin_GPIO10)
#define DEFAULT_SPI_BUS_MOSI (&pin_GPIO11)
#define DEFAULT_SPI_BUS_MISO (&pin_GPIO8)

#define MICROPY_HW_LED_STATUS (&pin_GPIO12)
