USB_VID = 0x239A
USB_PID = 0x80E6
USB_PRODUCT = "MagTag"
USB_MANUFACTURER = "Adafruit"

INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = MPZ

# The default queue depth of 16 overflows on release builds,
# so increase it to 32.
CFLAGS += -DCFG_TUD_TASK_QUEUE_SZ=32

CIRCUITPY_ESP_FLASH_MODE=dio
CIRCUITPY_ESP_FLASH_FREQ=40m
CIRCUITPY_ESP_FLASH_SIZE=4MB

CIRCUITPY_MODULE=wrover
MICROPY_PY_ASYNC_AWAIT = 0
CIRCUITPY_ATEXIT = 0
CIRCUITPY_AUDIOBUSIO = 0
CIRCUITPY_AUDIOBUSIO_I2SOUT = 0
CIRCUITPY_BITBANGIO = 0
CIRCUITPY_BLEIO_HCI = 0
CIRCUITPY_BLEIO = 0
CIRCUITPY_CANIO = 0
CIRCUITPY_FRAMEBUFFERIO = 0
CIRCUITPY_COUNTIO = 0
CIRCUITPY_MSGPACK = 0
CIRCUITPY_SYNTHIO = 0
CIRCUITPY_VECTORIO = 0
CIRCUITPY_QRIO = 0
CIRCUITPY_BITMAPTOOLS = 0
CIRCUITPY_TRACEBACK = 0
CIRCUITPY_IMAGECAPTURE = 0
CIRCUITPY_GETPASS = 0
CIRCUITPY_RGBMATRIX = 0
