USB_VID = 0x2886
USB_PID = 0x802d
USB_PRODUCT = "Seeeduino Wio Terminal"
USB_MANUFACTURER = "Seeed"

CHIP_VARIANT = SAMD51P19A
CHIP_FAMILY = samd51

QSPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICES = "W25Q32JVxQ"
LONGINT_IMPL = MPZ

CIRCUITPY__EVE = 1
CIRCUITPY_CODEOP = 0
CIRCUITPY_FLOPPYIO = 0
CIRCUITPY_JPEGIO = 0
CIRCUITPY_MSGPACK = 0
CIRCUITPY_PARALLELDISPLAYBUS = 0
CIRCUITPY_RGBMATRIX = 0
CIRCUITPY_SHARPDISPLAY = 0
CIRCUITPY_SYNTHIO = 0
CIRCUITPY_VECTORIO = 0
