name: Run Zephyr tests

on:
  workflow_call:
    inputs:
      cp-version:
        required: true
        type: string

jobs:
  zephyr:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    env:
      CP_VERSION: ${{ inputs.cp-version }}
    steps:
      - name: Set up repository
        uses: actions/checkout@v6
        with:
          submodules: false
          show-progress: false
          fetch-depth: 1
      - name: Set up python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13
      - name: Set up Zephyr
        uses: ./.github/actions/deps/ports/zephyr-cp
      - name: Set up submodules
        id: set-up-submodules
        uses: ./.github/actions/deps/submodules
        with:
          target: zephyr-cp
      - name: Set up external
        uses: ./.github/actions/deps/external
      - name: Build native sim target
        run: make -C ports/zephyr-cp -j2 BOARD=native_native_sim
      - name: Build bsim
        run: make -j 2 everything
        working-directory: ports/zephyr-cp/tools/bsim
      - name: Build native_nrf5340bsim
        run: make -C ports/zephyr-cp -j2 BOARD=native_nrf5340bsim
      - name: Build native_nrf54lm20bsim
        run: make -C ports/zephyr-cp -j2 BOARD=native_nrf54lm20bsim
      - name: Run Zephyr tests
        run: make -C ports/zephyr-cp test
